### ISSUE TITLE
Add test target in the root Makefile

### ISSUE THREAD

**Issue by iamazeem** [liquidaty/zsv#13]
Add `test` target in the root `Makefile`.
`make test` would build/rebuild `zsv` and runs its tests.
The same can be used in the CI workflow.

**Comment by liquidaty** [comment]
s/b fixed now, lmk if not. Thanks!

**Comment by iamazeem** [comment]
Thank you! :+1: 

`make test` is working now.
But, these tests are failing:

```text
test-select-7: Passed
/tmp/test-select-7.out2 expected/test-select-7.out2 differ: byte 10, line 2
test-select-7: Failed!
/tmp/test-select-7.out3 expected/test-select-7.out3 differ: byte 10, line 2
test-select-7: Failed!
test-select-8: 
test-select-8: Passed
/tmp/test-select-8.out2 expected/test-select-8.out2 differ: byte 16, line 2
test-select-8: Failed!
/tmp/test-select-8.out3 expected/test-select-8.out3 differ: byte 16, line 2
test-select-8: Failed!
test-select-9: 
(zsv_select) 1: Could not open for reading: ~/zsv/data/test/quoted3.csv
make[2]: *** [Makefile:162: test-select-9] Error 1
make[2]: Leaving directory '~/zsv/app/test'
make[1]: *** [Makefile:315: test-select] Error 2
make[1]: Leaving directory '~/zsv/app'
make: *** [Makefile:57: test] Error 2
```

**Comment by liquidaty** [comment]
thank you! s/b fixed now as of 126ec3343b97770c29f86815f18cc12f9cfc6145, please run `git pull && ./configure && gmake clean uninstall test`

(or make instead of gmake as appropriate)

**Comment by iamazeem** [comment]
Some tests are still failing:

```text
/tmp/test-select-7.out2 expected/test-select-7.out2 differ: byte 10, line 2
test-select-7: Failed!
/tmp/test-select-7.out3 expected/test-select-7.out3 differ: byte 10, line 2
test-select-7: Failed!
test-select-8: 
test-select-8: Passed
/tmp/test-select-8.out2 expected/test-select-8.out2 differ: byte 16, line 2
test-select-8: Failed!
/tmp/test-select-8.out3 expected/test-select-8.out3 differ: byte 16, line 2
test-select-8: Failed!
```

Also, there is this line:

```text
/bin/sh: 1: [: test-sql: unexpected operator
```

which is being repeated for each test.

It can be fixed by replacing `==` with `=` in `app/test/Makefile:188`.

**Comment by iamazeem** [comment]
Also, `#!/bin/sh` is missing in `app/test/select-quotebuff-gen.sh`.

**Comment by liquidaty** [comment]
what platform/compiler are you seeing failed tests for select-7 tests on?

**Comment by iamazeem** [comment]
Platform: Linux (Ubuntu 20.04, GCC: 10.3.0)

Though the tests are failing, the return code is ZERO.
Shouldn't the return code be a failure?

**Comment by iamazeem** [comment]
**Update on tests**

OS: Ubuntu 18.04 and 20.04
GCC: 10.3.0
Clang: 12.0.0

All tests are passing for **Linux/gcc**.

However, for **Linux/clang**, getting segfault:

```text
test-echo: 
Segmentation fault (core dumped)
make[2]: *** [Makefile:100: test-echo] Error 139
```

**Comment by liquidaty** [comment]
Not quite sure why clang works on OSX but not other platforms; for now, please limit build/test to gcc; we will document and update configure accordingly.

**Comment by liquidaty** [comment]
>  Though the tests are failing, the return code is ZERO. Shouldn't the return code be a failure?

Yes, will update that

**Comment by liquidaty** [comment]
Should all be fixed now in 6f4a7c067d02242e344e5defd26e0be418d2dac6, pls lmk if not

**Comment by iamazeem** [comment]
> Should all be fixed now in [6f4a7c0](https://github.com/liquidaty/zsv/commit/6f4a7c067d02242e344e5defd26e0be418d2dac6), pls lmk if not

By "all", you mean that tests should now be passed when compiled with `clang` too?

**Comment by iamazeem** [comment]
**FYI**: Linux/clang build is disabled now.

Did some debugging and memory profiling with `gdb` and `valgrind` on **Linux/clang** build.
Compiled code with `CFLAGS='-g3 -ggdb -O0'`.

For `clang`, in  `src/vector_delim.c` file at line # **33**:

```c
    memcpy(&str_simd, pSrc1 + i, VECTOR_BYTES);
```

the memory address `pSrc1 + i` seems to be the culprit here.

**gdb output**

```text
$ gdb ./build/Linux/rel/clang/bin/zsv_echo
...
(gdb) r < ./data/loans_1.csv
...
Program received signal SIGSEGV, Segmentation fault.
vec_delims (s=0x409490 "rubbish -->,http://www.sec.gov/xxx", ',' <repeats 132 times>, "131,132,133", ',' <repeats 23 times>..., n=<optimized out>, char_match1=<optimized out>, char_match2=<optimized out>, char_match3=<optimized out>, 
    char_match4=<optimized out>, maskp=<optimized out>) at ./vector_delim.c:33
33	    memcpy(&str_simd, pSrc1 + i, VECTOR_BYTES);
(gdb) bt
#0  vec_delims (s=0x409490 "rubbish -->,http://www.sec.gov/xxx", ',' <repeats 132 times>, "131,132,133", ',' <repeats 23 times>..., n=<optimized out>, char_match1=<optimized out>, char_match2=<optimized out>, char_match3=<optimized out>, 
    char_match4=<optimized out>, maskp=<optimized out>) at ./vector_delim.c:33
#1  zsv_scan_delim (scanner=0x4092f0, buff=0x409490 "rubbish -->,http://www.sec.gov/xxx", ',' <repeats 132 times>, "131,132,133", ',' <repeats 23 times>..., bytes_read=131072) at ./zsv_internal.c:293
#2  zsv_scan (scanner=0x4092f0, scanner@entry=0x7ffff7f786c0 <_IO_2_1_stdout_>, buff=0x409490 "rubbish -->,http://www.sec.gov/xxx", ',' <repeats 132 times>, "131,132,133", ',' <repeats 23 times>..., bytes_read=<optimized out>) at ./zsv_internal.c:417
#3  0x00000000004032f0 in zsv_parse_more (scanner=<optimized out>) at zsv.c:108
#4  0x0000000000401aa3 in main (argc=1, argv=<optimized out>) at echo.c:76
```

**valgrind output**

```shell
$ valgrind --track-origins=yes --show-leak-kinds=all  ~/zsv/build/Linux/rel/clang/bin/zsv_echo < ./data/loans_1.csv
==809030== Memcheck, a memory error detector
==809030== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==809030== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==809030== Command: ~/zsv/build/Linux/rel/clang/bin/zsv_echo
==809030== 
==809030== 
==809030== Process terminating with default action of signal 11 (SIGSEGV)
==809030==  General Protection Fault
==809030==    at 0x40274D: vec_delims (vector_delim.c:33)
==809030==    by 0x40274D: zsv_scan_delim (zsv_internal.c:293)
==809030==    by 0x40274D: zsv_scan (zsv_internal.c:417)
==809030==    by 0x401AA2: main (echo.c:76)
==809030== 
==809030== HEAP SUMMARY:
==809030==     in use at exit: 418,272 bytes in 5 blocks
==809030==   total heap usage: 6 allocs, 1 frees, 422,368 bytes allocated
==809030== 
==809030== LEAK SUMMARY:
==809030==    definitely lost: 0 bytes in 0 blocks
==809030==    indirectly lost: 0 bytes in 0 blocks
==809030==      possibly lost: 0 bytes in 0 blocks
==809030==    still reachable: 418,272 bytes in 5 blocks
==809030==         suppressed: 0 bytes in 0 blocks
==809030== Rerun with --leak-check=full to see details of leaked memory
==809030== 
==809030== For lists of detected and suppressed errors, rerun with: -s
==809030== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by liquidaty** [comment]
Will review thanks!

**Comment by liquidaty** [comment]
Think this may be resolved-- could you pls try branch `clang`, commit 6c904ec4125ee641f041ce8596a42fd1dc0fdf68?

**Comment by iamazeem** [comment]
> Think this may be resolved-- could you pls try branch `clang`, commit [6c904ec](https://github.com/liquidaty/zsv/commit/6c904ec4125ee641f041ce8596a42fd1dc0fdf68)?

Tested branch https://github.com/liquidaty/zsv/commits/clang for Linux/clang locally and all tests passed successfully. :+1:

**Comment by liquidaty** [comment]
Merged with main
